# Generated by Django 3.0.3 on 2020-03-15 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200315_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approve_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 14, 19, 34, 351252, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 14, 19, 34, 351252, tzinfo=utc)),
        ),
    ]
